/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SigninRouteImport } from './routes/signin'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as BookMeetingRouteImport } from './routes/book-meeting'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as IndexBak2RouteImport } from './routes/index.bak2'
import { Route as IndexBakRouteImport } from './routes/index.bak'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SigninRoute = SigninRouteImport.update({
  id: '/signin',
  path: '/signin',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const BookMeetingRoute = BookMeetingRouteImport.update({
  id: '/book-meeting',
  path: '/book-meeting',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexBak2Route = IndexBak2RouteImport.update({
  id: '/index/bak2',
  path: '/index/bak2',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexBakRoute = IndexBakRouteImport.update({
  id: '/index/bak',
  path: '/index/bak',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/book-meeting': typeof BookMeetingRoute
  '/contact': typeof ContactRoute
  '/services': typeof ServicesRoute
  '/signin': typeof SigninRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/index/bak': typeof IndexBakRoute
  '/index/bak2': typeof IndexBak2Route
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/book-meeting': typeof BookMeetingRoute
  '/contact': typeof ContactRoute
  '/services': typeof ServicesRoute
  '/signin': typeof SigninRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/index/bak': typeof IndexBakRoute
  '/index/bak2': typeof IndexBak2Route
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/book-meeting': typeof BookMeetingRoute
  '/contact': typeof ContactRoute
  '/services': typeof ServicesRoute
  '/signin': typeof SigninRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/index/bak': typeof IndexBakRoute
  '/index/bak2': typeof IndexBak2Route
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/book-meeting'
    | '/contact'
    | '/services'
    | '/signin'
    | '/sitemap.xml'
    | '/index/bak'
    | '/index/bak2'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/book-meeting'
    | '/contact'
    | '/services'
    | '/signin'
    | '/sitemap.xml'
    | '/index/bak'
    | '/index/bak2'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/book-meeting'
    | '/contact'
    | '/services'
    | '/signin'
    | '/sitemap.xml'
    | '/index/bak'
    | '/index/bak2'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  BookMeetingRoute: typeof BookMeetingRoute
  ContactRoute: typeof ContactRoute
  ServicesRoute: typeof ServicesRoute
  SigninRoute: typeof SigninRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  IndexBakRoute: typeof IndexBakRoute
  IndexBak2Route: typeof IndexBak2Route
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signin': {
      id: '/signin'
      path: '/signin'
      fullPath: '/signin'
      preLoaderRoute: typeof SigninRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/book-meeting': {
      id: '/book-meeting'
      path: '/book-meeting'
      fullPath: '/book-meeting'
      preLoaderRoute: typeof BookMeetingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/index/bak2': {
      id: '/index/bak2'
      path: '/index/bak2'
      fullPath: '/index/bak2'
      preLoaderRoute: typeof IndexBak2RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/index/bak': {
      id: '/index/bak'
      path: '/index/bak'
      fullPath: '/index/bak'
      preLoaderRoute: typeof IndexBakRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  BookMeetingRoute: BookMeetingRoute,
  ContactRoute: ContactRoute,
  ServicesRoute: ServicesRoute,
  SigninRoute: SigninRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  IndexBakRoute: IndexBakRoute,
  IndexBak2Route: IndexBak2Route,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
